export const CONST_TRANSITION = {
  SERVICE_THUMBNAIL_PREFIX: 'BOOKING_SERVICE_THUMBNAIL_',
  SERVICE_NAME_PREFIX: 'SERVICE_NAME_PREFIX',
  SERVICE_DESCRIPTION_PREFIX: 'SERVICE_DESCRIPTION_PREFIX',
  SERVICE_RATING_PREFIX: 'SERVICE_RATING_PREFIX',

  RESOURCE_IMAGE_PREFIX: 'RESOURCE_IMAGE_PREFIX_',
  RESOURCE_NAME_PREFIX: 'RESOURCE_NAME_PREFIX_',
  RESOURCE_DESCRIPTION_PREFIX: 'RESOURCEDESCRIPTIONE_PREFIX_',

  BOOKING_SUBMIT_BUTTON_PREFIX: 'BOOKING_SUBMIT_BUTTON_',

  AUTH_LOGO: 'AUTH_LOGO',
  AUTH_TITLE: 'AUTH_TITLE',
  AUTH_DESCRIPTION: 'AUTH_DESCRIPTION',

  CURRENT_USER_AVATAR: 'CURRENT_USER_AVATAR',
  CURRENT_USER_NAME: 'CURRENT_USER_NAME',

  BOOKING_NAME_PREFIX: 'BOOKING_NAME_PREFIX_',
  BOOKING_STATUS_PREFIX: 'BOOKING_STATUS_PREFIX_',
};
